# ContentBox Site Example with Docker Compose.
version: "3"

services:
  contentbox:
    image: ortussolutions/contentbox
    # Environment Variables
    environment:
      # cfconfig_adminPassword: contentbox
      install: "true"
      # Database Connection
      DB_CONNECTION_STRING: "jdbc:mysql://cb_database:3306/contentbox?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=true"
      DB_CLASS: "org.gjt.mm.mysql.Driver"
      DB_USER: "contentbox" 
      DB_PASSWORD: "contentbox"
    # Ports
    ports:
      - "8080:8080"
    # Data & Overrides
    volumes:
      # Persist Media Manager
      - ./docker/contentbox-content:/app/includes/shared/media

  # Database
  cb_database:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: contentbox
       MYSQL_DATABASE: contentbox
       MYSQL_USER: contentbox
       MYSQL_PASSWORD: contentbox
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql