version: "3"

services:

  # Database
  cb_database:
    image: mysql:latest  
    environment:
       MYSQL_ROOT_PASSWORD: contentbox
       MYSQL_DATABASE: contentbox
       MYSQL_USER: contentbox
       MYSQL_PASSWORD: contentbox
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
  
  # Distributed Cache
  cb_cache:
    image: redis
    ports:
        - "6379:6379"
    volumes:
      - ./docker/redis:/data
  
  # ContentBox Site
  contentbox:
    depends_on:
      - cb_database
      - cb_cache
    image: ortussolutions/contentbox
    
    # Environment Variables
    environment:
      # Admin passowrd
      cfconfig_adminPassword: contentbox
      # Make sure your dependencies get installed
      BOX_INSTALL: "true"
      # Run installer on first run, then comment this out
      install: "true"
      # Distributed Cache Name: distributed -> Redis look in config/CacheBox.cfc
      DISTRIBUTED_CACHE: "distributed"
      # Database Connection
      DB_CONNECTION_STRING: "jdbc:mysql://cb_database:3306/contentbox?useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=true"
      DB_CLASS: "org.gjt.mm.mysql.Driver"
      DB_USER: "contentbox" 
      DB_PASSWORD: "contentbox"
   
    # Ports
    ports:
      - "8080:8080"
   
    # Data & Overrides
    volumes:
      # Persist Media Manager
      - ./docker/contentbox-content:/app/includes/shared/media
      # Overrides for Distributed Caching, make sure you use a centralized DB instead of HSQL
      - ./box.json:/app/box.json
      - ./config/CacheBox.cfc:/app/config/CacheBox.cfc
      - ./config/Coldbox.cfc:/app/config/Coldbox.cfc
      # Uncomment for custom modules
      #- ./modules_app:/app/modules_app